---
- name: Determine if Nmap is available from Debian Backports
  ansible.builtin.set_fact:
    nmap_available_from_backports: >-
      {{
        ansible_distribution == "Debian"
        and ansible_distribution_release in ["bullseye", "bookworm"]
      }}

- name: Install nmap
  ansible.builtin.package:
    name: nmap
  # With the below boolean expression we use a minimal version of:
  # not nmap_available_from_backports or not nmap_install_from_backports
  when: not (nmap_available_from_backports and nmap_install_from_backports)

- name: Install nmap from Debian Backports
  when:
    - nmap_available_from_backports
    - nmap_install_from_backports
  block:
    - name: Add the Debian Backports repository
      ansible.builtin.include_role:
        name: backports

    - name: Install nmap
      ansible.builtin.apt:
        default_release: "{{ ansible_distribution_release }}-backports"
        name: nmap
