---
- name: Install nmap
  ansible.builtin.package:
    name: nmap
  # yamllint/ansible-lint complains about this being too long, but
  # there is no clean way to break it up.
  #
  # yamllint disable-line rule:line-length
  when: not (ansible_distribution == "Debian" and ansible_distribution_release in ["bullseye", "bookworm"])

- name: Install nmap from Debian Backports
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release in ["bullseye", "bookworm"]
  block:
    - name: Add the Debian Backports repository
      ansible.builtin.include_role:
        name: backports

    - name: Install nmap
      ansible.builtin.apt:
        default_release: "{{ ansible_distribution_release }}-backports"
        name: nmap
