---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-nmap
      ansible.builtin.include_role:
        name: ansible-role-nmap
      vars:
        nmap_install_from_backports: false
